### ISSUE TITLE
"currentEditorTab is null" on startup

### ISSUE THREAD

**Issue by democat3457** [xarkenz/mars-red#2]
The following exception occurs when starting the program:
```
% java -jar mars-red-v5.0-beta1-jar-with-dependencies.jar
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "mars.venus.editor.FileEditorTab.getFileStatus()" because the return value of "mars.venus.editor.EditTab.getCurrentEditorTab()" is null
	at mars.venus.VenusUI.setMenuState(VenusUI.java:522)
	at mars.venus.execute.ExecuteTab.setProgramStatus(ExecuteTab.java:181)
	at mars.venus.VenusUI.setProgramStatus(VenusUI.java:865)
	at mars.venus.editor.EditTab$FileOpener.openFiles(EditTab.java:752)
	at mars.venus.editor.EditTab.openFiles(EditTab.java:278)
	at mars.venus.editor.EditTab.loadWorkspaceState(EditTab.java:223)
	at mars.venus.VenusUI.<init>(VenusUI.java:258)
	at mars.MarsLauncher.lambda$launchGUI$0(MarsLauncher.java:202)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
After some digging, I believe the problem stems from the fact that the EditTab has no selected component on initialization. It seems that the VenusUI expects there to be a non-null FileEditorTab that has NO_FILE set as the FileStatus upon initialization, but the selected component is null, thus returning a null FileEditorTab and causing the error. It also appears that FileEditorTab never actually gets constructed with NO_FILE set as the status - all usages of its constructor are when opening files or creating new files, and thus set the file status immediately after construction.

**Comment by xarkenz** [comment]
I think that was just an oversight on my part when I split `ProgramStatus` off from `FileStatus`. When there are no files open, `EditTab.getCurrentEditorTab()` returns `null`, and the GUI's menu state *should* be set to `FileStatus.NO_FILE`, but I never handled that case properly in `VenusUI.setMenuState(ProgramStatus)`.

**Comment by xarkenz** [comment]
Should be fixed with the latest commit. This is what the method looks like now, with the null check added:

```java
public void setMenuState(ProgramStatus status) {
    switch (status) {
        case NOT_ASSEMBLED -> {
            FileEditorTab currentEditorTab = this.getMainPane().getEditTab().getCurrentEditorTab();
            if (currentEditorTab != null) {
                this.setMenuState(currentEditorTab.getFileStatus());
            }
        }
        case NOT_STARTED, PAUSED -> this.setMenuStateRunnable();
        case RUNNING -> this.setMenuStateRunning();
        case TERMINATED -> this.setMenuStateTerminated();
    }
}

**Comment by democat3457** [comment]
Do you want to call setMenuInitial if current == null?

**Comment by xarkenz** [comment]
Yes, probably a good idea. I will add that to the next commit.
